### ISSUE TITLE
Fix babel vulnerability

### ISSUE THREAD

**Issue by vprince1** [aws-solutions-library-samples/distributed-compute-on-aws-with-cross-regional-dask#8]
A new "critical severity" vulnerability was identified recently for `@babel/traverse`. More details are in https://github.com/advisories/GHSA-67hx-6x53-jw92. Since your repository is using this package, kindly fix it at the earliest.

**Comment by oconpa** [comment]
Packaged removed: https://github.com/aws-solutions-library-samples/distributed-compute-on-aws-with-cross-regional-dask/pull/9
